# This is a basic workflow to help you get started with Actions

name: Build


# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildLinux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      
      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          chmod +x ./setup/unish-lib.sh
          sh ./setup/unish-lib.sh
      - name: Skip SScript setup mode
        run: |
          echo -n 'oy9:showMacroty8:loopCosti25y10:includeAllfg' > ~/settings.cocoa
          cat ~/settings.cocoa
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build linux --app-version="4.0.0-${{ github.run_id}}" -D officialBuild
        continue-on-error: true
      - name: Zip Files
        if: always()
        run: |
          mkdir -p export/release/linux/bin
          zip -r Linux-Engine.zip export/release/linux/bin
        continue-on-error: true
      - name: Publish Artifact
        if: always()
        uses: actions/upload-artifact@v4.3.4
        with:
          name: linuxBuild
          path: 'export/release/linux/bin'
        continue-on-error: true
      - name: Publish Linux Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v4.0.0-${{ github.run_id }}"
          name: "Engine Build v4.0.0-${{ github.run_id }}"
          body: "Automated multi-platform compilation builds."
          draft: false
          prerelease: false
          files: Linux-Engine.zip
          
  buildWindows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          .\"setup/windows-lib.bat"
        shell: cmd
      - name: Skip SScript setup mode
        run: |
          echo oy9:showMacroty8:loopCosti25y10:includeAllfg > %USERPROFILE%\settings.cocoa
          type %USERPROFILE%\settings.cocoa
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"  -D officialBuild
        continue-on-error: true
      - name: Zip Files
        if: always()
        run: |
          New-Item -ItemType Directory -Force -Path export/release/windows/bin
          New-Item -ItemType File -Force -Path export/release/windows/bin/placeholder.txt
          Compress-Archive -Path export/release/windows/bin/* -DestinationPath Windows-Engine.zip -Force
        shell: pwsh
        continue-on-error: true
      - name: Publish Artifact
        if: always()
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windowsBuild
          path: export/release/windows/bin
        continue-on-error: true
      - name: Publish Windows Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v4.0.0-${{ github.run_id }}"
          name: "Engine Build v4.0.0-${{ github.run_id }}"
          draft: false
          prerelease: false
          files: Windows-Engine.zip

  buildMac:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          chmod +x ./setup/unish-lib.sh
          sh ./setup/unish-lib.sh
      - name: Skip SScript setup mode
        run: |
          echo -n 'oy9:showMacroty8:loopCosti25y10:includeAllfg' > ~/settings.cocoa
          cat ~/settings.cocoa
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build mac --app-version="4.0.0-${{ github.run_id}}" -D officialBuild
        continue-on-error: true
      - name: Zip Files
        if: always()
        run: |
          mkdir -p export/release/macos/bin
          zip -r Mac-Engine.zip export/release/macos/bin
        continue-on-error: true
      - name: Publish Artifact
        if: always()
        uses: actions/upload-artifact@v4.3.4
        with:
          name: macBuild
          path: export/release/macos/bin
        continue-on-error: true
      - name: Publish Mac Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v4.0.0-${{ github.run_id }}"
          name: "Engine Build v4.0.0-${{ github.run_id }}"
          draft: false
          prerelease: false
          files: Mac-Engine.zip

  buildAndroid:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      
      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Install Android SDK 35 and NDK r27d
        run: |
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-35" "build-tools;35.0.0" "ndk;27.0.12077973" "cmdline-tools;latest"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/27.0.12077973" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/27.0.12077973" >> $GITHUB_ENV
      
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          chmod +x ./setup/unish-lib.sh
          sh ./setup/unish-lib.sh
      
      - name: Setup Lime for Android
        run: |
          haxelib run lime setup android
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_SDK_ROOT/ndk/27.0.12077973
          haxelib run lime config JAVA_HOME $JAVA_HOME
      
      - name: Skip SScript setup mode
        run: |
          echo -n 'oy9:showMacroty8:loopCosti25y10:includeAllfg' > ~/settings.cocoa
          cat ~/settings.cocoa
      
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      
      - name: Clean old build artifacts only
        run: |
          rm -rf export
          rm -rf build
          rm -rf ~/.gradle
      
      - name: Compile
        run: haxelib run lime build android --app-version="4.0.0-${{ github.run_id}}" -D officialBuild -D HXCPP_IGNORE_WARNINGS
        continue-on-error: true
      
      - name: Isolate Android Package
        if: always()
        run: |
          mkdir -p export/release/android/bin/app/build/outputs/apk/release
          touch export/release/android/bin/app/build/outputs/apk/release/placeholder.apk
          find export/release/android/bin/app/build/outputs/apk/release -name "*.apk" -exec cp {} ./Engine-Android.apk \;
        continue-on-error: true
      - name: Publish Artifact
        if: always()
        uses: actions/upload-artifact@v4.3.4
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release
        continue-on-error: true
      - name: Publish Android Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v4.0.0-${{ github.run_id }}"
          name: "Engine Build v4.0.0-${{ github.run_id }}"
          draft: false
          prerelease: false
          files: Engine-Android.apk

  buildIOS:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          chmod +x ./setup/unish-lib.sh
          sh ./setup/unish-lib.sh
      
      - name: Skip SScript setup mode
        run: |
          echo -n 'oy9:showMacroty8:loopCosti25y10:includeAllfg' > ~/settings.cocoa
          cat ~/settings.cocoa
      
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      
      - name: Compile
        run: haxelib run lime build ios -nosign --app-version="4.0.0-${{ github.run_id}}" -D officialBuild
        continue-on-error: true
      
      - name: Isolate iOS Package
        if: always()
        run: |
          mkdir -p Payload export/release/ios/build/Release-iphoneos
          mkdir -p export/release/ios/build/Release-iphoneos/placeholder.app
          find export/release/ios/build/Release-iphoneos -name "*.app" -exec cp -r {} ./Payload/ \;
          zip -r Engine-iOS.ipa ./Payload
        continue-on-error: true
      - name: Publish Artifact
        if: always()
        uses: actions/upload-artifact@v4.3.4
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos
        continue-on-error: true
      - name: Publish iOS Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v4.0.0-${{ github.run_id }}"
          name: "Engine Build v4.0.0-${{ github.run_id }}"
          draft: false
